### ISSUE TITLE
Unable to edit hosts or pf.conf file using the same. 

### ISSUE THREAD

**Issue by nikhilpande-tudip** [sveinbjornt/STPrivilegedTask#11]
Hi,
I am trying to edit hosts file. But it gives error "sudo: no tty present and no askpass program specified".
I have tried but its not working. Please help if anyone know. 
Thank You.

**Comment by sveinbjornt** [comment]
Hey,
You can't use sudo in STPrivilegedTask, since it prompts for password input
via STDIN.
All best,
Sveinbjorn

**Comment by nikhilpande-tudip** [comment]
Thanks for the reply @sveinbjornt. Do you know if there's any other way to achieve this?

**Comment by sveinbjornt** [comment]
A few years back, It used to be possible to feed the password to sudo via STDIN, but if I remember correctly this was blocked due to security concerns in 10.4 or 10.5.

If you just want to edit the hosts file, you don't need to invoke sudo.  Running a script such as:

#/bin/sh
echo "127.0.0.1 facebook.com" >> /etc/hosts

via STPrivilegedTask works just fine.

**Comment by nikhilpande-tudip** [comment]
Thanks @sveinbjornt. It worked for me.
